version: 2.1  # Ensure this is at the top of your config

jobs:
  build:
    docker:
      - image: cimg/python:3.9  # Use a Docker image with Python installed
    steps:
      - checkout  # Step to checkout the code
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt  # Install dependencies
      - run:
          name: Run tests
          command: pytest  # Run tests with pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build  # Run the "build" job
